/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d9e3f2",
        surface: "#fcf9f8",
        "secondary-fixed": "#d9e3f2",
        "primary-fixed-dim": "#b2c5ff",
        "on-surface-variant": "#434654",
        "surface-variant": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#001848",
        "on-secondary-fixed-variant": "#3e4853",
        background: "#fcf9f8",
        secondary: "#555f6c",
        "tertiary-container": "#575b5e",
        "surface-container-high": "#eae7e7",
        "on-primary-container": "#c4d2ff",
        "on-tertiary-container": "#d0d3d6",
        "primary-fixed": "#dae2ff",
        tertiary: "#404446",
        "surface-tint": "#0c56d0",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "outline-variant": "#c3c6d6",
        "inverse-on-surface": "#f3f0ef",
        "on-error": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "on-surface": "#1c1b1b",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#181c1e",
        "secondary-fixed-dim": "#bdc7d6",
        "on-error-container": "#93000a",
        "on-secondary-container": "#5b6572",
        "on-secondary-fixed": "#131c27",
        "tertiary-fixed": "#e0e3e6",
        "tertiary-fixed-dim": "#c3c7ca",
        "on-tertiary-fixed-variant": "#43474a",
        outline: "#737685",
        "inverse-surface": "#313030",
        "primary-container": "#0052cc",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#0040a2",
        "surface-dim": "#dcd9d9",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        primary: "#003d9b",
        "on-background": "#1c1b1b",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        unit: "4px",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
